### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by michaeljoser** [nickolayrusev/livescore-cli#1]
Hello,

I think livescore changed their markup because livescore-cli dont work anymore :(

**Comment by nickolayrusev** [comment]
Hi, thanks for the contribution. Yes you are wright, they changed they markup and livescore-cli stopped work. Tomorrow will try to find spare time to fix it ;) pull requests are welcome also. Have a nice day

**Comment by michaeljoser** [comment]
Hi,

I had a crack at fixing it but looking at the source html i don't see any matches - only placeholders,  they seem to use a template technology (probably to prevent crawlers) :(

not sure if we can crawl it anymore.

**Comment by nickolayrusev** [comment]
I think I found a way but I should check if it's legal. May be I should put their logo somewhere ;)

**Comment by nickolayrusev** [comment]
I fixed it. You can update and check if everything is okay. Thanks for the contribution :)
