### ISSUE TITLE
Match Detail

### ISSUE THREAD

**Issue by melihberberolu** [nickolayrusev/livescore-cli#4]
Hi,
How can i get match detail ? What is the request endpoint 
( uri: 'http://m.livescore.com/~~/app1-home/soccer/?tz='+ tz +'&tzout=' + tz + '/MATCHDETAIL_ID', ) ??

**Comment by nickolayrusev** [comment]
:) sorry I was unavailable. If you have additional questions feel free to ask. If I can I will help :)
